service: sudoku-generator-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11

# you can overwrite defaults here
  stage: dev
  region: us-west-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "dynamodb:*"
     Resource: "arn:aws:dynamodb:*:*:table/sudoku_puzzles*"

package:
  artifact: target/sudokugenerator-lambda-dev.jar

functions:
  generate-puzzle-bulk:
    handler: kh.sudoku.generatorlambda.SudokuBulkGeneratorHandler
    timeout: 30
    events:
      - schedule:
          rate: cron(0 8 * * ? *)
          input:
            puzzles : "2"
            targetGivens : "17"
      - schedule:
          rate: cron(30 8 * * ? *)
          input:
            puzzles : "2"
            targetGivens : "18"
      - schedule:
          rate: cron(0 9 * * ? *)
          input:
            puzzles : "2"
            targetGivens : "19"
      - schedule:
          rate: cron(30 9 * * ? *)
          input:
            puzzles : "2"
            targetGivens : "20"
    

# you can add CloudFormation resource templates here
resources:
  Resources:
    SudokuPuzzlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sudoku_puzzles
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: difficulty
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: difficulty
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: PuzzleByDifficultyIndex
            KeySchema: 
              - AttributeName: difficulty
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - puzzle
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
